import { Box, Button, Container, HStack, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { useSession, signIn, signOut } from 'next-auth/react';

const Home: NextPage = () => {
  const name = trpc.useQuery(['user.getName']);
  const role = trpc.useQuery(['user.getRole']);

  const { data: session } = useSession();
  const changeRole = trpc.useMutation(['user.changeRole']);

  const changeRoleClick = () => {
    changeRole.mutate();
  };

  return (
    <>
      <Head>
        <title>nextauth test</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container bg={'blue.200'}>
        <Text>{!name.isLoading && name.data}</Text>
        <Text>{!role.isLoading && role.data}</Text>
        <HStack p={3}>
          {!session && <Button onClick={() => signIn()}>Sign in</Button>}

          {session && <Button onClick={() => signOut()}>Sign out</Button>}

          {session && (
            <Button onClick={() => changeRoleClick()}>Change Role</Button>
          )}
        </HStack>
      </Container>
    </>
  );
};

export default Home;
